services:
  db:
    container_name: veerify-db
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: veerify
      POSTGRES_PASSWORD: veerifypassword
      POSTGRES_DB: veerifydb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  mail-tester:
    container_name: veerify-mail-tester
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'
  valkey:
    container_name: veerify-valkey
    image: valkey/valkey:9
    ports:
      - '6379:6379'
    volumes:
      - valkey_data:/data
  minio:
    container_name: veerify-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
  minio-setup:
    container_name: veerify-minio-setup
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 minioadmin minioadmin; do
        echo 'waiting for minio...';
        sleep 1;
      done;
      mc mb --ignore-existing local/veerify-assets;
      mc anonymous set download local/veerify-assets;
      "

volumes:
  db_data:
  valkey_data:
  minio_data:
