export const selectors = {
  loginEmail: '[data-testid="login-email"]',
  loginPassword: '[data-testid="login-password"]',
  loginSubmit: '[data-testid="login-submit"]',
  loginError: '[data-testid="login-error"]',
  settingsTabProfile: '[data-testid="settings-tab-profile"]',
  settingsTabSecurity: '[data-testid="settings-tab-security"]',
  settingsTabNotifications: '[data-testid="settings-tab-notifications"]',
  settingsTabOrganization: '[data-testid="settings-tab-organization"]',
  settingsTabTeam: '[data-testid="settings-tab-team"]',
  settingsTabBilling: '[data-testid="settings-tab-billing"]',
  settingsTabAppearance: '[data-testid="settings-tab-appearance"]',
  settingsBillingPanel: '[data-testid="settings-billing-panel"]',
  billingContactsInput: '[data-testid="billing-contacts-input"]',
  billingContactsAdd: '[data-testid="billing-contacts-add"]',
  billingContactsSave: '[data-testid="billing-contacts-save"]',
  billingContactItem: '[data-testid="billing-contact-item"]',
  teamTitle: '[data-testid="team-title"]',
  teamNameInput: '#team-name',
  teamMembersCount: '[data-testid="team-members-count"]',
  teamOpenCreateDialog: '[data-testid="team-open-create-dialog"]',
  teamCreateName: '[data-testid="team-create-name"]',
  teamCreateSubmit: '[data-testid="team-create-submit"]',
  teamSwitcherTrigger: '[data-testid="team-switcher-trigger"]',
  teamSwitcherActiveName: '[data-testid="team-switcher-active-name"]',
  teamSwitcherActiveOrg: '[data-testid="team-switcher-active-org"]',
  navUserLoading: '[data-testid="nav-user-loading"]',
  navUserTrigger: '[data-testid="nav-user-trigger"]',
  navUserName: '[data-testid="nav-user-name"]',
  navUserEmail: '[data-testid="nav-user-email"]',
  organizationTitle: '[data-testid="organization-title"]',
  organizationNameInput: '[data-testid="organization-name-input"]',
  organizationSlugInput: '[data-testid="organization-slug-input"]',
  organizationLogoInput: '[data-testid="organization-logo-input"]',
  organizationSave: '[data-testid="organization-save"]',
  organizationMembersCount: '[data-testid="organization-members-count"]',
  organizationOpenDeleteDialog: '[data-testid="organization-open-delete-dialog"]',
  organizationDeleteConfirmInput: '[data-testid="organization-delete-confirm-input"]',
  organizationDeleteSubmit: '[data-testid="organization-delete-submit"]',
  feedbackPageTitle: '[data-testid="feedback-page-title"]',
  feedbackProductsFilterTrigger: '[data-testid="feedback-products-filter-trigger"]',
  feedbackProductsFilterAll: '[data-testid="feedback-products-filter-all"]',
  feedbackViewKanban: '[data-testid="feedback-view-kanban"]',
  feedbackViewTable: '[data-testid="feedback-view-table"]',
  feedbackStatusFilter: '[data-testid="feedback-status-filter"]',
  feedbackSortFilter: '[data-testid="feedback-sort-filter"]',
  feedbackTable: '[data-testid="feedback-table"]',
  feedbackAddButton: '[data-testid="feedback-add-button"]',
  feedbackLoading: '[data-testid="feedback-loading"]',
  feedbackError: '[data-testid="feedback-error"]',
  feedbackEmpty: '[data-testid="feedback-empty"]',
  feedbackList: '[data-testid="feedback-list"]',
  feedbackKanban: '[data-testid="feedback-kanban"]',
  feedbackKanbanOpenColumn: '[data-testid="feedback-kanban-column-open"]',
  feedbackCreateTitle: '[data-testid="feedback-create-title"]',
  feedbackCreateBody: '[data-testid="feedback-create-body"]',
  feedbackCreateCategory: '[data-testid="feedback-create-category"]',
  feedbackCreateSubmit: '[data-testid="feedback-create-submit"]',
  feedbackDeleteConfirm: '[data-testid="feedback-delete-confirm"]',
  feedbackStatTotal: '[data-testid="feedback-stat-total"]',
}

export const teamSwitcherItemSelector = (teamId: string) => `[data-testid="team-switcher-item-${teamId}"]`
export const feedbackItemSelector = (id: string) => `[data-testid="feedback-item-${id}"]`
export const feedbackItemDeleteSelector = (id: string) => `[data-testid="feedback-item-delete-${id}"]`
