import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import * as yaml from 'js-yaml'

export type OpenAPIRoutePaths = Record<string, Record<string, unknown>>

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const DEFAULT_ROUTE_DIR = path.resolve(SCRIPT_DIR, '..', 'server', 'api')
const DEFAULT_OUTPUT_FILE = path.resolve(SCRIPT_DIR, '..', 'server', 'generated', 'openapi-routes.ts')

function stripJSDocPrefix(line: string): string {
  return line.replace(/^\s*\* ?/, '')
}

/**
 * Parse the YAML document carried by a route's `@openapi` JSDoc block.
 *
 * The route comments intentionally use the same path-item shape as
 * swagger-jsdoc. Keeping this parser independent from Nitro means the
 * resulting data can be generated before Nitro bundles the server.
 */
export function extractOpenAPIDocument(source: string, fileName = 'route.ts'): OpenAPIRoutePaths {
  const comment = source.match(/\/\*\*([\s\S]*?)\*\//g)?.find((block) => /@openapi\b/.test(block))

  if (!comment) {
    throw new Error(`No @openapi JSDoc block found in ${fileName}`)
  }

  const lines = comment.slice(3, -2).split('\n').map(stripJSDocPrefix)
  const openapiLine = lines.findIndex((line) => /^@openapi\b/.test(line.trim()))

  if (openapiLine === -1) {
    throw new Error(`No @openapi marker found in ${fileName}`)
  }

  const yamlText = lines
    .slice(openapiLine + 1)
    .join('\n')
    .trim()

  if (!yamlText) {
    throw new Error(`Empty @openapi JSDoc block in ${fileName}`)
  }

  const document = yaml.load(yamlText)

  if (!document || typeof document !== 'object' || Array.isArray(document)) {
    throw new Error(`Expected an OpenAPI path map in ${fileName}`)
  }

  return document as OpenAPIRoutePaths
}

async function findRouteFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true })
  const files: string[] = []

  for (const entry of entries) {
    const entryPath = path.join(directory, entry.name)
    if (entry.isDirectory()) {
      files.push(...(await findRouteFiles(entryPath)))
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      files.push(entryPath)
    }
  }

  return files.sort()
}

/** Scan all route files and merge path items in stable file order. */
export async function scanOpenAPIRoutes(routeDir = DEFAULT_ROUTE_DIR): Promise<OpenAPIRoutePaths> {
  const paths: OpenAPIRoutePaths = {}
  const routeFiles = await findRouteFiles(routeDir)

  for (const routeFile of routeFiles) {
    const source = await readFile(routeFile, 'utf8')
    if (!/@openapi\b/.test(source)) continue

    const document = extractOpenAPIDocument(source, path.relative(routeDir, routeFile))

    for (const [routePath, pathItem] of Object.entries(document)) {
      if (!routePath.startsWith('/')) {
        throw new Error(`OpenAPI path must start with "/" in ${path.relative(routeDir, routeFile)}: ${routePath}`)
      }
      if (!pathItem || typeof pathItem !== 'object' || Array.isArray(pathItem)) {
        throw new Error(`OpenAPI path item must be an object in ${path.relative(routeDir, routeFile)}: ${routePath}`)
      }

      const existingPathItem = (paths[routePath] ??= {})
      for (const [method, operation] of Object.entries(pathItem)) {
        if (method in existingPathItem) {
          throw new Error(`Conflicting OpenAPI operation: ${method.toUpperCase()} ${routePath}`)
        }
        existingPathItem[method] = operation
      }
    }
  }

  return Object.fromEntries(Object.entries(paths).sort(([left], [right]) => left.localeCompare(right)))
}

export async function generateOpenAPIRoutes(
  options: {
    routeDir?: string
    outputFile?: string
  } = {}
): Promise<OpenAPIRoutePaths> {
  const paths = await scanOpenAPIRoutes(options.routeDir ?? DEFAULT_ROUTE_DIR)
  const outputFile = options.outputFile ?? DEFAULT_OUTPUT_FILE
  const output = `/** Generated by scripts/openapi-scanner.ts. Do not edit manually. */\nexport const openapiPaths = ${JSON.stringify(paths, null, 2)} as const\n`

  await mkdir(path.dirname(outputFile), { recursive: true })
  await writeFile(outputFile, output)
  return paths
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateOpenAPIRoutes()
    .then((paths) => {
      const operationCount = Object.values(paths).reduce((count, pathItem) => count + Object.keys(pathItem).length, 0)
      console.log(`Generated OpenAPI routes: ${Object.keys(paths).length} paths, ${operationCount} operations`)
    })
    .catch((error) => {
      console.error(error)
      process.exitCode = 1
    })
}
